<a href="https://colab.research.google.com/github/winrrr1/myfrontprj1/blob/main/%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pwd

/content


In [18]:
import numpy

In [19]:
import numpy as np

In [20]:
# help(np.array)

In [21]:
np.array([1,2,3])

array([1, 2, 3])

In [22]:
arr1=np.array([1,2,3])

In [23]:
type(arr1)

numpy.ndarray

In [24]:
arr1.shape

(3,)

In [25]:
arr1.size

3

In [31]:
arr1.ndim

1

In [26]:
arr2=np.array([[1,2,3], [4,5,6]])

In [27]:
arr2.shape

(2, 3)

In [28]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr2.size

6

In [30]:
arr2.ndim

2

In [32]:
arr3 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [33]:
arr3.ndim

3

In [34]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [35]:
arr3.size

12

In [36]:
arr3.shape

(2, 2, 3)

In [38]:
arr=np.array([[1],
              [2],
              [-1.0],
              [3.14]])

In [39]:
arr

array([[ 1.  ],
       [ 2.  ],
       [-1.  ],
       [ 3.14]])

In [40]:
arr.shape

(4, 1)

In [42]:
arr.ndim

2

In [43]:
arr4=np.array([[[1. , 2. ,-1. , 3.14]]])

In [44]:
arr4.ndim

3

In [45]:
arr4.shape

(1, 1, 4)

In [46]:
mu = np.array([1,2,3])

In [47]:
nu = np.array([4,4,4])

In [48]:
2*mu

array([2, 4, 6])

In [49]:
mu + nu

array([5, 6, 7])

In [50]:
2* (mu + nu)

array([10, 12, 14])

In [51]:
# 행렬의 연산

In [52]:
A=np.array([[3,6],
            [4,5]])

In [53]:
B=np.array([[5,8],
            [6,7]])

In [58]:
A+B

array([[ 8, 14],
       [10, 12]])

In [57]:
A-B

array([[-2, -2],
       [-2, -2]])

In [61]:
C=np.array([[5,8,9],
            [6,7,3]])

In [62]:
A+C

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [66]:
np.all([True, True, True])

True

In [67]:
np.all([True, True, False])

False

In [68]:
np.any([False, False, False])

False

In [69]:
np.any([True, False, False])

True